const USER_REGISTERED_QUEUE = "USER_REGISTERED";
const USER_DETAILS_REQUEST_QUEUE = "USER_DETAILS_REQUEST";
const USER_PROFILE_UPDATE_QUEUE = "USER_PROFITS_UPDATED";

export {
	USER_REGISTERED_QUEUE,
	USER_DETAILS_REQUEST_QUEUE,
	USER_PROFILE_UPDATE_QUEUE,
};
