const USER_REGISTERED_QUEUE = "USER_REGISTERED";
const USER_DETAILS_REQUEST_QUEUE = "USER_DETAILS_REQUEST";
const USER_PROFILE_UPDATE_QUEUE = "USER_PROFITS_UPDATED";
const PRODUCT_UPDATE_QUEUE = "PRODUCT_UPDATED";
const PRODUCT_REGISTERED_QUEUE = "PRODUCT_REGISTERED";
const ORDER_UPDATE_QUEUE = "ORDER_UPDATE";
const ORDER_REGISTERED_QUEUE = "ORDER_REGISTER";

export {
	USER_REGISTERED_QUEUE,
	USER_DETAILS_REQUEST_QUEUE,
	USER_PROFILE_UPDATE_QUEUE,
	PRODUCT_UPDATE_QUEUE,
	PRODUCT_REGISTERED_QUEUE,
	ORDER_REGISTERED_QUEUE,
	ORDER_UPDATE_QUEUE,
};
